name: Test

on:
  push:

jobs:
  Analyse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tree
      uses: actions/checkout@v5
    - name: Fail
      id: some-failure
      continue-on-error: true
      run: false
    - name: The normal path
      if: steps.some-failure.outcome != 'failure'
      run: true
