name: Test

on:
  push:

jobs:
  Analyse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tree
      uses: actions/checkout@v5
    - name: Fail
      continue-on-error: true
      run: false
    - name: After continue-on-error
      if: steps.plan.outcome == 'failure'
      run: true
    - name: The normal path
      if: steps.plan.outcome != 'failure'
      run: true
