name: Test

on:
  push:

jobs:
  Analyse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tree
      uses: actions/checkout@v5
    - name: Fail
      continue-on-error: true
      run: false
